version: '3'
services:
  db:
    image: "postgres:10.1"
    volumes:
     - ../data:/var/lib/postgresql/data
    environment:    #设置环境变量
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres
  web:
    build: ../src/
    ports:
     - "13017:13017"
    links:
     - db
